# -*- coding: utf-8 -*-

run:
  mode: test          # train / eval / predict / test
  data_parallel: true
  force_cpu: false

output:
  logs_root: logs
  ckpt_root: checkpoints

data:
  train_csv: "D:/kubota/Data/Model10test/filepath/train_df_20260226.csv"
  val_csv:   "D:/kubota/Data/model10test/filepath/val_df_20260226.csv"
  test_csv:  "D:/kubota/Data/model10test/filepath/test_df_20260226.csv"

  image_size: 256
  batch_size: 32
  val_batch_size: 32
  test_batch_size: 1

  shuffle_train: true
  shuffle_val: false

model:
  num_classes: 15 #0~14ならば15
  transformer_count: 6
  pretrained_unet_path: "D:/kubota/Data/Model10test/seg_result_20260227/best.pth"
  freeze_keywords: ["TCB1", "TCB2", "TCB3", "TCB4", "TCB5", "Trans"]
  multi_model: true #別々のモデルとして持つか。trueの場合別々、falseの場合一つ

train:
  epochs: 50
  train_original: true #originalを学習するかどうか。trueなら学習
  lr_original: 1.0e-4
  lr_ctnet: 1.0e-3
  optimizer: adam
  weight_decay: 0.0
  num_workers: 2
  amp: false
  detect_anomaly: true
  keep_frozen_transformer_eval: true
  save_every: 1
  log_every: 0

val:
  num_workers: 0
  monitor_slide: 150

eval:
  load_pth: "D:/kubota/Data/Model10test/Ablation_noRank/best.pth"
  save_predictions: true
  pred_dir: "D:/kubota/Data/Model10test/ablation_noRank_nii"
  
loss:
  name: condnet_sr  #mae/logmae/condnet_sr
  mean_loss: logmae
  
  lambda_stat: 1.0
  lambda_rank: 0 # 0.2
  lambda_smooth: 0.01 # 0.01

  w_mean: 0.99
  w_std: 0.01
  
  alpha: 0.7
  rank_pairs: 100